-- Script para inserir materiais iniciais no sistema CEDIME
-- Execute este SQL no SQL Editor do Supabase

-- Primeiro, vamos garantir que as categorias existam
INSERT INTO categories (name) VALUES
  ('MATERIAL DE LIMPEZA'),
  ('MATERIAL ESCOLAR'),
  ('GÁS')
ON CONFLICT (name) DO NOTHING;

-- Inserir materiais de limpeza
INSERT INTO materials (name, category, unit, quantity, min_quantity, unit_price) VALUES
  ('AMACIANTE', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('ÁLCOOL 70%', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('ÁGUA SANITÁRIA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('ÁLCOOL GEL', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('CERA LÍQUIDA INCOLOR', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('CLORO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('CONDICIONADOR INFANTIL', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('CREME DENTAL', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('CREME DERMATOLÓGICO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('DESINFETANTE', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('DETERGENTE', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('ESPONJA DE AÇO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('ESPONJA MULTIUSO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FLANELA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FÓSFORO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FRALDA G', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FRALDA GG', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FRALDA M', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FRALDA P', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FRALDA XG', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('FRALDA XXG', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('INSETICIDA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LÂMPADA LED 50W', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LENÇO UMEDECIDO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LIMPADOR MULTIUSO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LIXEIRA 10L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LIXEIRA 120L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LIXEIRA 240 L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LIXEIRA 50L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('LUVA LIMPEZA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('OLÉO INFANTIL', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PÁ DE LIXO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PANO CHÃO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PANO DE PRATO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PANO LIMPEZA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PAPEL ALUMÍNIO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PAPEL HIGIENICO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PAPEL INTERFOLHADO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PAPEL TOALHA BANHEIRO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PAPEL TOALHA COZINHA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PLAFONIER', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('PREGADOR DE ROUPA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('REGULADOR DE GÁS', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('RODO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('ROLO SACOLA ALIMENTO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SABÃO DE COCO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SABÃO EM BARRA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SABÃO EM PO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SABONETE LÍQUIDO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SACO LIXO 100L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SACO LIXO 200L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SACO LIXO 50L', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('SHAMPOO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('TALCO', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('TOUCA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),
  ('VASSOURA', 'MATERIAL DE LIMPEZA', 'Unidade', 0, 0, 0),

-- Inserir materiais escolares
  ('APLICADOR DE COLA QUENTE', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('A4 COLORIDO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('A4 BRANCO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('APAGADOR P/ QUADRO BRANCO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('APONTADOR', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('APONTADOR COM DEPOSITO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('BASTÃO COLA QUENTE FINA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('BASTÃO COLA QUENTE GROSSA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('BLOCO PEDIDO COMERCIAL', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('BORRACHA BRANCA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CADERNO BROCHURA PEQUENO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CADERNO DE CALIGRAFIA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CADERNO UNIVERSITARIO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CAIXA P/ARQUIVO MORTO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CANETA BPS', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CANETA ESFEROGRÁFICA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CANETA QUADRO AZUL', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CANETA QUADRO PRETA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CANETA QUADRO VERMELHA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CANETINHA HIDROCOR', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CAPA ENCADERNAÇÃO PRETA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CAPA ENCADERNAÇÃO TRANSPARENTE', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CARTOLINA DUPLA FACE', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CLIPS 1/0', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CLIPS 2/0', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CLIPS 3/0', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CLIPS 4/0', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLA BASTÃO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLA BRANCA 500G', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLA BRANCA 90G', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLA COLORIDA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLA GLITTER', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLA ISOPOR', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLOR JET BRANCO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLOR JET CINZA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLOR JET DOURADO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLOR JET PRATA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLOR JET PRETO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('COLOR JET VERMELHO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('CORRETIVO FITA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('ENVELOPE A4 BRANCO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('ENVELOPE A4 OURO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('ENVELOPE PLASTICO A4', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('EVA FOSCO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('EVA GLITTER', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('FITA ADESIVA 12MM', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('FITA ADESIVA 48MM', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('FITA ADESIVA 48MM MARROM', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('FITA ADESIVA COLORIDA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('FITA CREPE BRANCA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('FOLHA A4 ADESIVA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GIZ DE CERA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GRAMPEADOR ALICATE', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GRAMPEADOR ROCAMA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GRAMPO 106/6', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GRAMPO 23/13', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GRAMPO 26/6', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('GRAMPO DE PASTA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('LÁPIS DE COR', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('LÁPIS JUMBO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('LÁPIS PRETO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('LIVRO DE ATA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('LIVRO DE PONTO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('MARCA TEXTO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('MASSA MODELAR', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PAPEL BRANCO 40KG', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PAPEL MICRO ONDULADO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PAPEL OURO 40K', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PASTA CATÁLOGO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PASTA COM GRAMPO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PASTA LISA TRANSPARENTE', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PASTA PAPELÃO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PASTA USPENSA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PEN DRIVE 16G', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PEN DRIVE 32G', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PENAS COLORIDAS', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PERFURADOR DE PAPEL', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PINCEL 08', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PINCEL 12', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PINCEL 20', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PINCEL PERMANENTE AZUL', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PINCEL PERMANENTE PRETO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PINCEL PERMANENTE VERMELHO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('PORTA DOCUMENTOS', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('RÉGUA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('TESOURA ESCOLAR', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('TESOURA ESCRITÓRIO', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('TINTA QUADRO AZUL', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('TINTA QUADRO PRETA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('TINTA QUADRO VERMELHA', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),
  ('TNT', 'MATERIAL ESCOLAR', 'Unidade', 0, 0, 0),

-- Inserir materiais de gás
  ('P13', 'GÁS', 'Unidade', 0, 0, 0),
  ('P45', 'GÁS', 'Unidade', 0, 0, 0);

-- Comentário
COMMENT ON TABLE materials IS 'Tabela de materiais do CEDIME - Dados iniciais inseridos';

